export const CUISINE_OPTIONS  = [
    "Italian",
    "Chinese",
    "Japanese",
    "Mexican",
    "Indian",
    "French",
    "Thai",
    "Spanish",
    "Greek",
    "Lebanese",
    "Turkish",
    "Moroccan",
    "Korean",
    "Vietnamese",
    "Ethiopian",
    "Brazilian",
    "Argentinian",
    "Peruvian",
    "Caribbean",
    "German",
    "Russian",
    "Polish",
    "Swedish",
    "Danish",
    "Portuguese",
    "Filipino",
    "Indonesian",
    "Malaysian",
    "Singaporean",
    "Israeli",
    "Egyptian",
    "Persian",
    "Afghan",
    "Pakistani",
    "Bangladeshi",
    "Sri Lankan",
    "Nepalese",
    "Tibetan",
    "Australian",
    "South African",
    "Eritrean",
    "Somali",
    "Sudanese",
    "Nigerian",
    "Ghanaian",
    "Kenyan",
    "Tanzanian",
    "Ugandan",
    "Algerian",
    "Tunisian"
  ] as const;
  