interface CuisineOption {
    value: string;
    label: string;
  }


export const cuisines: CuisineOption[] = [
    { value: "Italian", label: "Italian" },
    { value: "Chinese", label: "Chinese" },
    { value: "Japanese", label: "Japanese" },
    { value: "Mexican", label: "Mexican" },
    { value: "Indian", label: "Indian" },
    { value: "French", label: "French" },
    { value: "Thai", label: "Thai" },
    { value: "Spanish", label: "Spanish" },
    { value: "Greek", label: "Greek" },
    { value: "Lebanese", label: "Lebanese" },
    { value: "Vietnamese", label: "Vietnamese" },
    { value: "Turkish", label: "Turkish" },
    { value: "Korean", label: "Korean" },
    { value: "Moroccan", label: "Moroccan" },
    { value: "Ethiopian", label: "Ethiopian" },
    { value: "Brazilian", label: "Brazilian" },
    { value: "Argentinian", label: "Argentinian" },
    { value: "Peruvian", label: "Peruvian" },
    { value: "Caribbean", label: "Caribbean" },
    { value: "Cuban", label: "Cuban" },
    { value: "Filipino", label: "Filipino" },
    { value: "Malaysian", label: "Malaysian" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Pakistani", label: "Pakistani" },
    { value: "Bangladeshi", label: "Bangladeshi" },
    { value: "Persian (Iranian)", label: "Persian (Iranian)" },
    { value: "German", label: "German" },
    { value: "Russian", label: "Russian" },
    { value: "Polish", label: "Polish" },
    { value: "Ukrainian", label: "Ukrainian" },
    { value: "Hungarian", label: "Hungarian" },
    { value: "Czech", label: "Czech" },
    { value: "Austrian", label: "Austrian" },
    { value: "Swiss", label: "Swiss" },
    { value: "Belgian", label: "Belgian" },
    { value: "Dutch", label: "Dutch" },
    { value: "Scandinavian (Swedish, Norwegian, Danish)", label: "Scandinavian (Swedish, Norwegian, Danish)" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Australian", label: "Australian" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "American", label: "American" },
    { value: "Canadian", label: "Canadian" },
    { value: "South African", label: "South African" },
    { value: "Nigerian", label: "Nigerian" },
    { value: "Kenyan", label: "Kenyan" },
    { value: "Ghanaian", label: "Ghanaian" },
    { value: "Eritrean", label: "Eritrean" },
    { value: "Tunisian", label: "Tunisian" }
  ];